### ISSUE TITLE
Keys not processed

### ISSUE THREAD

**Issue by Sleepy-Jedi** [alac/txt_to_dataset#1]
Sensory Detail and Moment-to-Moment Detail always show up as null in the json output files. They never have an output from Oogabooga. I tried editing full_prompt.txt to add the keys to the examples but I keep getting list index out of range errors.
Side note is it possible to customize keys? 
Also, this is an awesome project, I tried something similar and failed horribly.

**Comment by alac** [comment]
Yeah, at some point I deleted Sensory Detail and Moment-to-Moment Detail from the full_prompt and forgot to delete the keys from the `settings.toml`. (They're a little too ambiguous to be useful imo.) But, I tried adding them back just now and it worked. 
Prompt keys just need to be added to each example in the same order, if not the AI will get confused. I tested just now and was able to add "Location".
`settings.toml` has `json_key_order` and `allowed_fields`. If you remove a key, you should remove it from there; that's what was causing the `null` valued keys to show up.

Hope this helps. If you still have problems, attach or inline the inputs and outputs.

**Comment by Sleepy-Jedi** [comment]
Awesome, thanks got it working! Now I think I figured out the problem from when I did it before. I was lazy so I just fed full_prompt.txt to chatgpt and had it add new sections to it. Looks like it replaced the last two lines with a whole new story.
